apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: MyAssaignment
  labels:
    app: myapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: aamirpinger/helloworld
        ports:
        - containerPort: 80




